title:            PyLadies Brasil
description:      "Ninguém pode fazer você se sentir inferior sem o seu consentimento (Eleanor Roosevelt)"
logo:             pyladies-avatar.png
disqus_shortname: pyladiesbrasil
share:            true
dropcap:			    true
encoding:         utf-8
permalink:        pretty

# Owner/author information
owner:
  name:           PyLadies Brasil
  avatar:         avatar.png
  email:          brazil@pyladies.com
  description:    "Ninguém pode fazer você se sentir inferior sem o seu consentimento (Eleanor Roosevelt)"
  twitter:        PyLadiesBrazil
  facebook:       PyLadiesBrazil
  github:         pyladies-brazil 
  google_plus:    https://plus.google.com/u/1/115115103611376880963/posts

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-58961512-1
google_verify:
# https://ssl.bing.com/thewebmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in navigation
# For external links add external: true
links:
  - title: Sobre
    url: /about
  - title: Blog
    url: /featured
  - title: Eventos
    url: /events
  - title: Locais
    url: /locations
  - title: Ladies
    url: /ladies

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Fortaleza
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    3
paginate_path: "page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


include: [".htaccess"]
exclude: ["config.ru","vendor","lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
